spring:
  application:
    name: demo-student-docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psql-container:5432/mydb
    username: myuser
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
